### ISSUE TITLE
App crashes instead of displaying a ToolTip

### ISSUE THREAD

**Issue by toastmonster** [FireCubeStudios/FluentFlyouts#11]
When moving the mouse over the icon and hovering there for more than a very short amount of time, the app crashes.  Normally I would expect it to display a ToolTip.

Running on Windows 10 x64 21H2.  Laptop is a Lenovo Thinkpad X230.

Here are the relevant logs from Event Viewer:

> Application: FluentFlyouts3.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IToolTipMethods.set_IsOpen(IObjectReference _obj, Boolean value)
   at Microsoft.UI.Xaml.Controls.ToolTip.set_IsOpen(Boolean value)
   at H.NotifyIcon.TaskbarIcon.OnToolTipChange(Object sender, Boolean visible)
   at H.NotifyIcon.Core.MessageWindow.ProcessWindowMessage(UInt32 msg, WPARAM wParam, LPARAM lParam)
   at H.NotifyIcon.Core.MessageWindow.OnWindowMessageReceived(HWND hWnd, UInt32 msg, WPARAM wParam, LPARAM lParam)

---

> Faulting application name: FluentFlyouts3.exe, version: 1.0.0.0, time stamp: 0x62b2f9e3
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2006, time stamp: 0xa5d20e5c
Exception code: 0xe0434352
Fault offset: 0x0012cc12
Faulting process ID: 0x14dc
Faulting application start time: 0x01d8dccb8be2870c
Faulting application path: C:\Program Files\WindowsApps\2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j\FluentFlyouts3\FluentFlyouts3.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 278db0a1-1d0c-40cc-b88d-f906f26cb95e
Faulting package full name: 2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j
Faulting package-relative application ID: App

---

> Fault bucket 2059785053577809388, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0
Problem signature:
P1: 2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j
P2: praid:App
P3: 1.0.0.0
P4: 62b2f9e3
P5: KERNELBASE.dll
P6: 10.0.19041.2006
P7: a5d20e5c
P8: e0434352
P9: 0012cc12
P10: 
Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER93AD.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER964E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER967E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER967C.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER96AC.tmp.txt
These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_2505FireCubeStud_9c7189903a5b68a36b2f2dd8d9c91fd762515_3d6e99fd_7366a28b-4120-4d5e-80f3-f92d4c0761ed
Analysis symbol: 
Rechecking for solution: 0
Report Id: 278db0a1-1d0c-40cc-b88d-f906f26cb95e
Report Status: 268435456
Hashed bucket: d18e2992f0a012e9cc95d397d02a0dec
Cab Guid: 0

---

**Comment by FireCubeStudios** [comment]
This might be a big ask but would it be possible for you to compile this app in your machine and check where within the application an error pops up?

**Comment by toastmonster** [comment]
Sorry, although I do work in IT I'm not a developer and have never compiled anything.

**Comment by FireCubeStudios** [comment]
oof. Ok I will try to add more error checking but I don't know why there is an issue

**Comment by FireCubeStudios** [comment]
I sent an update 3.1.9.0 to store that should arrive by tommorow and adds additional error handling. Please check if that one works

**Comment by FireCubeStudios** [comment]
ok the 3.1.9.0 update is out please try it

**Comment by FireCubeStudios** [comment]
The app no longer crashes when showing tooltips in v4
